version: '3'
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: aws-dyndns-php-0.1
    restart: always
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      AUTORUN_ENABLED: false
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_DOMAIN_NAME: ${AWS_DOMAIN_NAME}
      AWS_HOSTED_ZONE_ID: ${AWS_HOSTED_ZONE_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE}
      PHP_SESSION_COOKIE_SECURE: 0
      RATE_LIMIT: ${RATE_LIMIT}
      SSL_MODE: off
    networks:
      - traefik-network
    volumes:
      - 'php-storage:/var/www/html/storage'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.aws-dyndns-php.rule=Host(`${HOST_NAME}`)'
      - 'traefik.http.routers.aws-dyndns-php.entrypoints=websecure'
      - 'traefik.http.routers.aws-dyndns-php.tls.certresolver=myresolver'
      - 'traefik.http.services.aws-dyndns-php.loadbalancer.server.port=80'

networks:
  traefik-network:
    external: true

volumes:
  php-storage:
    driver: local